addClassPath(".");
MAIN_DIRECTORY = new File(getSourceFileInfo()).getParentFile().getAbsolutePath();
String LOG_FILE = MAIN_DIRECTORY + "/log.txt";
long LONG_CLICK_DURATION = 500;
cd(MAIN_DIRECTORY);
addClassPath(".");
importCommands("main");
importCommands("gestures");
importCommands("actions");
importCommands("others");
importCommands("assist");
importCommands("helper");
importCommands("lib");
importCommands("lib.file");
importCommands("assist.helper");
importCommands("assist.dialog");
importCommands("event");
importCommands("global");
import android.view.accessibility.*;
if (debugMe == void) debugMe = false;
if (debugDelay == void) debugDelay = 1000;
if (findDelay == void) findDelay = 100;
if (debugSteps == void) debugSteps = false;
if (debugInfo == void) debugInfo = false;
if (includeAllMethods == void) includeAllMethods = false;
if (quickAddMode == void) quickAddMode = true;
if (stepDelay == void) stepDelay = 50;
if (waitNodesTimeout == void) waitNodesTimeout = 10000;
if (DISPLAY_ID == void) DISPLAY_ID = 0;
if (ENV == void) ENV = Environment();
if (NodeInfo == void) NodeInfo = NodeInfo();
if (WindowType == void) WindowInfo = WindowInfo();
if (logIncludeNode == void ) logIncludeNode = false;
if (limitParentLevel == void) limitParentLevel = 1;
if (includeAllWindows == void) includeAllWindows = false;
if (filterWindowType == void) filterWindowType = 0;